
const GET_SELLER="GET_SELLER"
const SHOW_DETAIL="SHOW_DETAIL"
const HIDE_DETAIL="HIDE_DETAIL"
const GET_GOODS='GET_GOODS'
const GET_Ratings='GET_Ratings'
const GET_ADD='GET_ADD'
const GET_DECRESE='GET_DECRESE'
const SELECT='SELECT';
const CHANGE_TYPES='CHANGE_TYPES';
const TOGGLE='TOGGLE';
export default {
	GET_SELLER,
	SHOW_DETAIL,
	HIDE_DETAIL,
	GET_GOODS,
	GET_ADD,
	GET_DECRESE,
	GET_Ratings
}